from devto import post_to_platform
import os
from dotenv import load_dotenv

load_dotenv()

print("Testing Dev.to Publishing...")
try:
    content = "This is a test blog post generated by LeetLog AI via API. If you see this, Dev.to integration is working perfectly!"
    response = post_to_platform("Test LeetLog AI Post", content)
    print("SUCCESS! Post created:")
    print(response.get("url"))
except Exception as e:
    print(f"FAILED: {e}")
